[package]
name = "monotrade-platform-rust"
version = "0.1.0"
authors = ["holbrook <wanghaikuo@gmail.com>"]
edition = "2018"

# build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "monotrade"
path = "src/lib.rs"

[dependencies]
# libc = "0.2"

[build-dependencies]
