[package]
name = "monotrade-platform-rust"
version = "0.1.0"
authors = ["holbrook <wanghaikuo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
